fix scp update
Add checking for scp process, set the download status to 'Failed' if it
is terminated with signal.

Currently there is no checking for scp process exit code, it should be
set to correct status in case terminated with signal.

Tested:
1. The update task will be finished with error status when update
terminated.
2. Next update task can be created after failure first.

Fixes jira https://redmine.mellanox.com/issues/4458182

Signed-off-by: Sean Zhang <xiazhang@nvidia.com>

diff --git a/scp-transfer b/scp-transfer
--- a/scp-transfer
+++ b/scp-transfer
@@ -141,8 +141,15 @@ if [ "$transfer_started" = true ]; then
     # There is a known bug related to running Dropbear SCP from the BMC.
     # When transferring files, the transfer may succeed, but an "Invalid Argument"
     # error is generated at the end.
-    transferStatus="xyz.openbmc_project.Common.DownloadProgress.DownloadStatus.Completed"
-    echo "Transfer completed"
+
+    # Check if the scp process exited with a signal
+    if [ $? -ge 128 ]; then
+        transferStatus="xyz.openbmc_project.Common.DownloadProgress.DownloadStatus.Failed"
+        echo "Transfer failed"
+    else
+        transferStatus="xyz.openbmc_project.Common.DownloadProgress.DownloadStatus.Completed"
+        echo "Transfer completed"
+    fi
     busctl set-property xyz.openbmc_project.Software.Download /xyz/openbmc_project/software xyz.openbmc_project.Common.DownloadProgress Status s $transferStatus
     busctl set-property xyz.openbmc_project.Software.Download /xyz/openbmc_project/software xyz.openbmc_project.Common.DownloadProgress Progress y 100
 fi
